version: '3'
services:
  client:
    container_name: debug_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
    container_name: debug_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futuregraph
      - PGHOST=db
      - PGPASSWORD=dataforSQLpassword
      - PGDATABASE=dataforSQL
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"


  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=dataforSQL
      - POSTGRES_USER=futuregraph
      - POSTGRES_PASSWORD=dataforSQLpassword
volumes:
  dbdata: